### PR TITLE
Some test fixes

### PR DESCRIPTION
**Pull request by imikemiller**
Added firestore seeds to get `Collection.query.test.js` and `Document.reactivePath.test.js` to pass. Not sure if this is the right approach. I considered putting the seeds up top in `beforeAll` and dumping them in `afterAll` but I didn't want to taint the rest of the tests so they are currently being seeded and dropped where I could see they were needed.

### CODE REVIEW

**Comment by imikemiller** [comment]
@IjzerenHein I have added the seed to the top of the tests but they are still failing. The `re-fetch` test fails and seems to be similar issue to the empty docs nonsense you were helping me with. Having said that if I run `npm test -- -t 're-fetch'` it passes which is confusing

**Comment by IjzerenHein** [comment]
Hey man, thanks for this Pull Request. I've decided to only use the relevant bits and re-implement the seed process for the sample-data differently. The PR its-self felt a bit messy, with unnecessary imports being added and duplicate seeds.
I've instead created a separate step for seeding the database, which is executed once before running the jest tests. When running `yarn test` the sample-data in `test.sampleData.json` is written to the firestore database, after which the tests are run. This makes running the tests a lot faster, and you can still run the tests without the seed-process (useful when debugging), by using `yarn jest`.
Anyway, appreciate the help a lot.
Cheers, Hein

**Comment by IjzerenHein** [comment]
> @IjzerenHein I have added the seed to the top of the tests but they are still failing. The `re-fetch` test fails and seems to be similar issue to the empty docs nonsense you were helping me with. Having said that if I run `npm test -- -t 're-fetch'` it passes which is confusing

So, I've tried to reproduce the issue you mentioned but am unable to. Could you maybe retest this with the latest master branch? For me, running wither `npm test` or `npm test -- -t 're-fetch'` always succeeds.

**Comment by IjzerenHein** [comment]
Also, thanks for the Donation mike, appreciate it a lot. Will add you to the list of sponsors 👍

**Comment by IjzerenHein** [comment]
Thanks dude!

**Pull request closed without merging**
